/*
 * Copyright (c) 2024 Nuvoton Technology Corporation.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#define DT_DRV_COMPAT nuvoton_npcm_pinctrl

#include "zephyr/devicetree.h"
#include <assert.h>
#include <zephyr/init.h>
#include <zephyr/kernel.h>
#include <zephyr/drivers/pinctrl.h>
#include <zephyr/dt-bindings/pinctrl/npcm-pinctrl.h>
#include <zephyr/drivers/gpio.h>
#include <soc.h>

#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(pinctrl_npcm, LOG_LEVEL_ERR);

/*
 * Multi-function pin data
 */
#define NPCM_PINCTRL_REG_SIZE 5
#define NPCM_PINCTRL_CFG_SIZE 6

#define NPCM_PINCTRL_REG_NULL 0xFFFF
#define NPCM_PINCTRL_CFG_NULL 0xFF

struct npcm_pinctrl_reg_cfg {
	uint16_t reg[NPCM_PINCTRL_REG_SIZE];
	uint8_t cfg[NPCM_PINCTRL_CFG_SIZE]; /* Bit n in cfg represents reg[n] bit value */
};

#define NPCM_PINCTRL_GROUP_RDATA(reg_group, alt_group)       {.reg = reg_group, .cfg = alt_group}
#define NPCM_PINCTRL_REG(reg4, reg3, reg2, reg1, reg0)       {reg0, reg1, reg2, reg3, reg4}
#define NPCM_PINCTRL_ALT(cfg0, cfg1, cfg2, cfg3, cfg4, cfg5) {cfg0, cfg1, cfg2, cfg3, cfg4, cfg5}

/*
 * Multi-function pin define for cfg0~cfg5.
 *
 * The GPIO should be the first alt function cfg0, which is the default selection for the GPIO
 * driver. The rest of the alt functions should be defined in the order of the alt function number.
 */
const struct npcm_pinctrl_reg_cfg npcm_pinctrl_table[] = {
	/* GPIOB0 / SMI */
	[GPIOB0__SMI] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5_6_SMI_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO00 / EMAC_RXD1 / CTSB / PWM7 */
	[GPIO00__EMAC_RXD1__CTSB__PWM7] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_EMC_CTL_0_RMII_EN, NPCM_PINCTRL_ALT9_4_CTS2_SL,
				 NPCM_PINCTRL_ALT5_1_PWM7_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO01 / EMAC_RXD0 / DSRB / TA7 */
	[GPIO01__EMAC_RXD0__DSRB__TA7] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_EMC_CTL_0_RMII_EN, NPCM_PINCTRL_ALT9_3_SP2CTL_SL,
				 NPCM_PINCTRL_ALT3_7_TA7_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO02 / EMAC_REF_CLK / RTSB / PWM8 */
	[GPIO02__EMAC_REF_CLK__RTSB__PWM8] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_EMCCTL_0_RMII_EN, NPCM_PINCTRL_ALT9_0_RTS2_SL,
				 NPCM_PINCTRL_ALT5_2_PWM8_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO03 / EMAC_TXD1 / DTRB / TA8 */
	[GPIO03__EMAC_TXD1__DTRB__TA8] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_EMC_CTL_0_RMII_EN, NPCM_PINCTRL_ALT9_3_SP2CTL_SL,
				 NPCM_PINCTRL_ALT4_0_TA8_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO04 / EMAC_TXD0 / SINB / CR_SIN1 / PWM1 */
	[GPIO04__EMAC_TXD0__SINB__CR_SIN1__PWM1] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_EMC_CTL_0_RMII_EN, NPCM_PINCTRL_ALT9_1_SP2I_SL,
				 NPCM_PINCTRL_ALTB_1_URTI_SL, NPCM_PINCTRL_ALT4_3_PWM1_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO05 / EMAC_TX_EN / SOUTB / CR_SOUT1 / TA1 */
	[GPIO05__EMAC_TX_EN__SOUTB__CR_SOUT1__TA1] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_EMC_CTL_0_RMII_EN, NPCM_PINCTRL_ALT9_2_SP2O_SL,
				 NPCM_PINCTRL_ALTA_6_URTO1_SL, NPCM_PINCTRL_ALT3_1_TA1_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO06 / EMAC_MDI0 / DCDB / PWM9 */
	[GPIO06__EMAC_MDI0__DCDB__PWM9] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_EMC_CTL_0_RMII_EN, NPCM_PINCTRL_ALT9_3_SP2CTL_SL,
				 NPCM_PINCTRL_ALT5_3_PWM9_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO07 / EMAC_MDC / RIB / TA9 */
	[GPIO07__EMAC_MDC__RIB__TA9] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_EMC_CTL_1_MDIO_EN, NPCM_PINCTRL_ALT9_5_RI2_SL,
				 NPCM_PINCTRL_ALT4_1_TA9_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOB1 / CLKRUN */
	[GPIOB1__CLKRUN] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT0_5_CLKRN_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIOB2 / LPCPD / ESPI_RST / LDRQ
	 * Set ESPI_EN strap pin for ESPI_RST.
	 */
	[GPIOB2__LPCPD__ESPI_RST__LDRQ] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT0_6_LPCPD_SL, NPCM_PINCTRL_ALTB_7_LDRQ_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIOB3 / ESPI_ALERT / SERIRQ
	 * Set ESPI_EN strap pin for eSPI_ALERT.
	 */
	[GPIOB3__ESPI_ALERT__SERIRQ] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT0_7_SERIRQ_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIOB7 / PLTRST
	 * Set ESPI_EN strap pin for GPIOB7.
	 */
	[GPIOB7__PLTRST] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOB4 */
	[GPIOB4] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOB5 */
	[GPIOB5] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO10 / CTSA */
	[GPIO10__CTSA] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTB_5_CTS1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO11 / SCL2A / DRSA */
	[GPIO11__SCL2A__DRSA] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTE_5_SMB2A_SL, NPCM_PINCTRL_ALTB_4_SP1CTL_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO12 / RTSA */
	[GPIO12__RTSA] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTB_0_RTS1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO13 / SDA2A / DTRA */
	[GPIO13__SDA2A__DTRA] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTE_5_SMB2A_SL, NPCM_PINCTRL_ALTB_4_SP1CTL_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO14 / SINA / CR_SIN1 */
	[GPIO14__SINA__CR_SIN1] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTB_2_SP1I_SL, NPCM_PINCTRL_ALTC_6_URTI1_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO15 / SOUTA / CR_SOUT1 / SOUTA_P80 */
	[GPIO15__SOUTA__CR_SOUT1__SOUTA_P80] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTB_3_SP1O_SL, NPCM_PINCTRL_ALTA_7_URTO2_SL,
				 NPCM_PINCTRL_ALTC_7_SOUTA_P80_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO16 / DCDA / SCL6B */
	[GPIO16__DCDA__SCL6B] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTB_4_SP1CTL_SL, NPCM_PINCTRL_ALT6D_7_SMB6B_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO17 / CLKOUT / RIA / SDA6B */
	[GPIO17__CLKOUT__RIA__SDA6B] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT7_6_CLKOUT_SL, NPCM_PINCTRL_ALTB_6_RI1_SL,
				 NPCM_PINCTRL_ALT6D_7_SMB6B_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOC0 / CR_SIN3 / SINC */
	[GPIOC0__CR_SIN3__SINC] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT31_6_URTI3_SL, NPCM_PINCTRL_ALT62_0_SINC_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOC1 / CR_SOUT3 / SOUTC */
	[GPIOC1__CR_SOUT3__SOUTC] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT31_7_URTO4_SL, NPCM_PINCTRL_ALT62_1_SOUTC_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOC2 / RTSC / SCL7A */
	[GPIOC2__RTSC__SCL7A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT62_2_RTSC_SL, NPCM_PINCTRL_ALT6D_0_SMB7A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOC3 / CTSC / SDA7A */
	[GPIOC3__CTSC__SDA7A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT62_3_CTSC_SL, NPCM_PINCTRL_ALT6D_0_SMB7A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOC4 / CR_SIN4 / SIND */
	[GPIOC4__CR_SIN4__SIND] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6C_0_URTI4_SL, NPCM_PINCTRL_ALT62_4_SIND_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOC5 / CR_SOUT4 / SOUTD */
	[GPIOC5__CR_SOUT4__SOUTD] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6C_1_URTO5_SL, NPCM_PINCTRL_ALT62_5_SOUTD_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOC6 / RTSD / SCL8A */
	[GPIOC6__RTSD__SCL8A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT62_6_RTSD_SL, NPCM_PINCTRL_ALT6D_1_SMB8A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOC7 / CTSD / SDA8A */
	[GPIOC7__CTSD__SDA8A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT62_7_CTSD_SL, NPCM_PINCTRL_ALT6D_1_SMB8A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOE3 */
	[GPIOE3] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO20 / MHZ_CLKIN / SLCT / YLW_LED */
	[GPIO20__MHZ_CLKIN__SLCT__YLW_LED] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6_7_UART_EXT_SEL, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALTE_7_YLW_LED_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO21 / BACK_CS / I3C1_SCL / DSRB / PE / CIRRX */
	[GPIO21__BACK_CS__I3C1_SCL__DSRB__PE__CIRRX] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT0_2_FIU_BACK_CS_SL, NPCM_PINCTRL_ALT10_6_I3C1_SL,
				 NPCM_PINCTRL_ALT6B_4_URTB_DSR_SL2, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALT7_1_CIRRX_SL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, 0x1)),
	/* GPIO22 / I3C1_SDA / DTRB / BUSY / P2_DGL */
	[GPIO22__I3C1_SDA__DTRB__BUSY__P2_DGL] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT10_0_CRGPIO_RST_SL,
				 NPCM_PINCTRL_ALT6B_5_URTB_DTR_SL2, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALT6_3_PORT80_SL, NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO23 / PVT_CS / I3C2_SCL / DCDB / ACK */
	[GPIO23__PVT_CS__I3C2_SCL__DCDB__ACK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT0_1_FIU_PVT_CS_SL, NPCM_PINCTRL_ALT10_1_I3C2_SL,
				 NPCM_PINCTRL_ALT6B_6_URTB_DTR_SL2, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO24 / I3C2_SDA / RIB / PD7 / P2_DGH */
	[GPIO24__I3C2_SDA__RIB__PD7__P2_DGH] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT10_1_I3C2_SL, NPCM_PINCTRL_ALT6B_7_RTB_RI_SL2,
				 NPCM_PINCTRL_ALT6_2_PRT_SL, NPCM_PINCTRL_ALT6_3_PORT80_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO25 / I3C3_SDA / PD6 / LED_A / SDA1B */
	[GPIO25__I3C3_SDA__PD6__LED_A__SDA1B] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT10_2_I3C3_SL, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALT6_3_PORT80_SL, NPCM_PINCTRL_ALTA_5_SMB1B_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO26 / I3C3_SCL / PD5 / LED_B / SCL1B */
	[GPIO26__I3C3_SCL__PD5__LED_B__SCL1B] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT10_2_I3C3_SL, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALT6_3_PORT80_SL, NPCM_PINCTRL_ALTA_5_SMB1B_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO27 / SMI / PD4 / LED_C / BEEP */
	[GPIO27__SMI__PD4__LED_C__BEEP] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT10_4_SMI_SL, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALT6_3_PORT80_SL, NPCM_PINCTRL_ALT6_1_BEEP_SEL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO30 / SINB / CR_SIN2 / PD3 / LED_D */
	[GPIO30__SINB__CR_SIN2__PD3__LED_D] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6B_0_URTB_SIN_SL2, NPCM_PINCTRL_ALT31_4_URTI2_SL,
				 NPCM_PINCTRL_ALT6_2_PRT_SL, NPCM_PINCTRL_ALT6_3_PORT80_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO31 / SOUTB / CR_SOUT2 / PD2 / LED_E */
	[GPIO31__SOUTB__CR_SOUT2__PD2__LED_E] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6B_1_URTB_SOUT_SL2, NPCM_PINCTRL_ALT31_5_URTO3_SL,
				 NPCM_PINCTRL_ALT6_2_PRT_SL, NPCM_PINCTRL_ALT6_3_PORT80_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO32 / RTSB / PD1 / LED_F / SCL9A */
	[GPIO32__RTSB__PD1__LED_F__SCL9A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6B_2_URTB_RTS_SL2, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALT6_3_PORT80_SL, NPCM_PINCTRL_ALT6D_2_SMB9A_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO33 / CTSB / PD0 / LED_G / SDA9A */
	[GPIO33__CTSB__PD0__LED_G__SDA9A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6B_3_URTB_CTS_SL2, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALT6_3_PORT80_SL, NPCM_PINCTRL_ALT6D_2_SMB9A_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIO34 / (SWDIO_1/CR_SOUT1) / SLIN / SCL5A
	 * See JTAG Hot-Plug HPLUG_CONN[3:0] for SWDIO_1/CR_SOUT1.
	 */
	[GPIO34__SWDIO_1_CR_SOUT1__SLIN__SCL5A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6_2_PRT_SL, NPCM_PINCTRL_ALTA_3_SMB5A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIO35 / (SWCLK_1/CR_SIN1) / INIT / P1_DGL / SDA5A
	 * See JTAG Hot-Plug HPLUG_CONN[3:0] for SWCLK_1/CR_SIN1.
	 */
	[GPIO35__SWCLK_1_CR_SIN1__INIT__P1_DGL__SDA5A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6_2_PRT_SL, NPCM_PINCTRL_ALT6_3_PORT80_SL,
				 NPCM_PINCTRL_ALTA_3_SMB5A_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO36 / ERR / VSBY_32KHZ_IN / PWM2 / SCL4A */
	[GPIO36__ERR__VSBY_32KHZ_IN__PWM2__SCL4A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6_2_PRT_SL, NPCM_PINCTRL_ALT7_5_EXT32KSL,
				 NPCM_PINCTRL_ALT4_4_PWM2_SL, NPCM_PINCTRL_ALTA_2_SMB4A_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO37 / AFD / P1_DGH / TA2 / SDA4A */
	[GPIO37__AFD__P1_DGH__TA2__SDA4A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6_2_PRT_SL, NPCM_PINCTRL_ALT6_3_PORT80_SL,
				 NPCM_PINCTRL_ALT3_2_TA2_SL, NPCM_PINCTRL_ALTA_2_SMB4A_SL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, 0x2, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOB6 / ECSCI / STB / GRN_LED */
	[GPIOB6__ECSCI__STB__GRN_LED] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT10_5_ECSCI_SL, NPCM_PINCTRL_ALT6_2_PRT_SL,
				 NPCM_PINCTRL_ALTE_6_GRN_LED_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIO40 / JTAG_TDI / DB_MOSI / MCLK
	 * Set JEN strap pin for JTAG_TDI, set FIU Gang for DB_MOSI.
	 */
	[GPIO40__JTAG_TDI__DB_MOSI__MCLK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTE_3_KBC_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIO41 / (SWCLK_0/CR_SIN1) / JTAG_TCK / DB_SCK / MDAT
	 * See JTAG Hot-Plug HPLUG_CONN[3:0] for SWCLK_0/CR_SIN1.
	 * Set JEN strap pin for JTAG_TCK.
	 * Set FIU Gang for DB_SCK.
	 */
	[GPIO41__SWCLK_0_CR_SIN1__JTAG_TCK__DB_SCK__MDAT] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTE_3_KBC_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0, 0, 0x10, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIO42 / JTAG_TDO / DB_MISO / KCLK
	 * Set JEN strap pin for JTAG_TDO, set FIU Gang for DB_MISO.
	 */
	[GPIO42__JTAG_TDO__DB_MISO__KCLK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTE_3_KBC_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIO43 / (SWDIO_0/CR_SOUT1) / JTAG_TMS / DB_SCE / KDAT
	 * See JTAG Hot-Plug HPLUG_CONN[3:0] for SWDIO_0/CR_SOUT1.
	 * Set JEN strap pin for JTAG_TMS.
	 * Set FIU Gang for DB_SCE.
	 */
	[GPIO43__SWDIO_0_CR_SOUT1__JTAG_TMS__DB_SCE__KDAT] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTE_3_KBC_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0, 0, 0x10, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO50 / PSOUT */
	[GPIO50__PSOUT] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5C_1_ACPI_GPIO50_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO51 / PSIN */
	[GPIO51__PSIN] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5C_0_ACPI_GPIO51_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPI52 / PSON */
	[GPIO52__PSON] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5C_2_ACPI_GPIO52_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO53 / SLP_S3 */
	[GPIO53__SLP_S3] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5F_0_ACPI_GPIO53_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO54 / PME / ECSCI */
	[GPIO54__PME__ECSCI] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5C_3_ACPI_GPIO54_SEL, NPCM_PINCTRL_ALT5_5_ECSCI_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, 0x18, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO44 / SHD_CS */
	[GPIO44__SHD_CS] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_3_SHD_SPI, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO45 / SHD_DIO0 */
	[GPIO45__SHD_DIO0] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_3_SHD_SPI, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO46 / SHD_DIO1 */
	[GPIO46__SHD_DIO1] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_3_SHD_SPI, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO47 / SHD_SCLK */
	[GPIO47__SHD_SCLK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_3_SHD_SPI, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO55 / SHD_DIO2 / WP_GPIO55 */
	[GPIO55__SHD_DIO2__WP_GPIO55] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_DEV_CTL3_1_WP_GPIO55,
				 NPCM_PINCTRL_ALTC_2_SHD_SPI_QUAD, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x8, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO56 / SHD_DIO3 */
	[GPIO56__SHD_DIO3] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_2_SHD_SPI_QUAD, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOE1 / DPWROK */
	[GPIOE1__DPWROK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5E_0_ACPI_GPIOE1_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOE0 / DEEP_S5 / 3VSBSW */
	[GPIOE0__DEEP_S5__3VSBSW] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5E_2_ACPI_GPIOE0_DEEP_S5_SEL,
				 NPCM_PINCTRL_ALT5E_5_ACPI_GPIOE0_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x18, 0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO60 / RSTOUT2 / SCL1A */
	[GPIO60__RSTOUT2__SCL1A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5D_2_ACPI_GPIO60_SEL, NPCM_PINCTRL_ALTA_0_SMB1A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, 0x18, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO61 / RSTOUT1 / SDA1A */
	[GPIO61__RSTOUT1__SDA1A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5D_1_ACPI_GPIO61_SEL, NPCM_PINCTRL_ALTA_0_SMB1A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, 0x18, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO62 / RSTOUT0 */
	[GPIO62__RSTOUT0] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5D_0_ACPI_GPIO62_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO63 / ATXPGD */
	[GPIO63__ATXPGD] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5F_2_ACPI_GPIO63_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOE2 / PWROK0 */
	[GPIOE2__PWROK0] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5E_3_ACPI_GPIOE2_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO57 */
	[GPIO57] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO64 / RESETCON / DPWROKI / PWM3 */
	[GPIO64__RESETCON__DPWROKI__PWM3] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5F_3_ACPI_GPIO64_SEL,
				 NPCM_PINCTRL_ALT9_6_DPWORK_SL, NPCM_PINCTRL_ALT4_5_PWM3_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, 0x4, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO65 / SLP_S5 */
	[GPIO65__SLP_S5] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5F_1_ACPI_GPIO65_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO66 / SPIP1_CLK */
	[GPIO66__SPIP1_CLK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_1_SPIP1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO67 / SPIP1_MOSI */
	[GPIO67__SPIP1_MOSI] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_1_SPIP1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO70 / SPIP1_DIO1 */
	[GPIO70__SPIP1_DIO1] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_1_SPIP1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIO71 / SLP_SUS
	 * Unset DSW_EN strap pin for GPIO71.
	 */
	[GPIO71__SLP_SUS] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5C_5_ACPI_GPIO71_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO72 / FW_RDY */
	[GPIO72__FW_RDY] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT7_0_GP72_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO73 / SPIP1_CS */
	[GPIO73__SPIP1_CS] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_1_SPIP1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOD0 / I3C4_SCL / SINE */
	[GPIOD0__I3C4_SCL__SINE] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT10_3_I3C4_SL, NPCM_PINCTRL_ALT66_0_SINE_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOD1 / I3C4_SDA / SOUTE */
	[GPIOD1__I3C4_SDA__SOUTE] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT10_3_I3C4_SL, NPCM_PINCTRL_ALT66_1_SOUTE_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOD2 / RTSE / SCL10A */
	[GPIOD2__RTSE__SCL10A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT66_2_RTSE_SL, NPCM_PINCTRL_ALT6D_3_SMB10A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOD3 / CTSE / SDA10A */
	[GPIOD3__CTSE__SDA10A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT66_3_CTSE_SL, NPCM_PINCTRL_ALT6D_3_SMB10A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOD4 / SINF / SCL11A */
	[GPIOD4__SINF__SCL11A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT66_4_SINF_SL, NPCM_PINCTRL_ALT6D_4_SMB11A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOD5 / SOUTF / SDA11A */
	[GPIOD5__SOUTF__SDA11A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT66_5_SOUTF_SL, NPCM_PINCTRL_ALT6D_4_SMB11A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOD6 / RTSF / SCL12A */
	[GPIOD6__RTSF__SCL12A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT66_6_RTSF_SL, NPCM_PINCTRL_ALT6D_5_SMB12A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOD7 / CTSF / SDA12A */
	[GPIOD7__CTSF__SDA12A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT66_7_CTSF_SL, NPCM_PINCTRL_ALT6D_5_SMB12A_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO74 / IOX1_LDSH */
	[GPIO74__IOX1_LDSH] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6A_0_SIOX1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO75 / IOX_DOUT */
	[GPIO75__IOX1_DOUT] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6A_0_SIOX1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO76 / WP_GPIO76 / SPIP1_DIO2 */
	[GPIO76__WP_GPIO76__SPIP1_DIO2] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_DEV_CTL3_2_WP_GPIO76, NPCM_PINCTRL_ALTC_1_SPIP1_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO77 / SPIP1_DIO3 */
	[GPIO77__SPIP1_DIO3] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTC_1_SPIP1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIO80 / KBC_TEST / PCHVSB
	 * Set DSW_EN strap pin for PCHVSB.
	 */
	[GPIO80__KBC_TEST__PCHVSB] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTE_0_KBC_TEST, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO81 / TA3 */
	[GPIO81__TA3] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT3_3_TA3_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOE4 / CASEOPEN */
	[GPIOE4__CASEOPEN] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5D_5_ACPI_GPIOE4_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOE5 / RSMRST */
	[GPIOE5__RSMRST] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5E_1_ACPI_GPIOE5_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOE6 / SKTOCC */
	[GPIOE6__SKTOCC] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5D_4_ACPI_GPIOE6_SEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO82 / I3C5_SCL / PWM0 */
	[GPIO82__I3C5_SCL__PWM0] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTA_4_I3C5_SL, NPCM_PINCTRL_ALT4_2_PWM0_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO83 / I3C5_SDA / TA0 */
	[GPIO83__I3C5_SDA__TA0] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTA_4_I3C5_SL, NPCM_PINCTRL_ALT3_0_TA0_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOF0 / SCL4B */
	[GPIOF0__SCL4B] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT34_6_RES, NPCM_PINCTRL_ALT6D_6_SMB4B_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOF1 / SDA4B */
	[GPIOF1__SDA4B] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT34_6_RES, NPCM_PINCTRL_ALT6D_6_SMB4B_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOF2 / IOX_DIN */
	[GPIOF2__IOX1_DIN] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6A_0_SIOX1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOF3 / IOX_SCLK */
	[GPIOF3__IOX1_SCLK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT6A_0_SIOX1_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO86 / VIN7 */
	[GPIO86__VIN7] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT1_7_VIN7_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO87 / VIN5 */
	[GPIO87__VIN5] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT1_5_VIN5_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO90 / (THR16/VIN16/TD2P) / DSMOUT */
	[GPIO90__THR16_VIN16_TD2P__DSMOUT] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT2_2_VIN16_SL, NPCM_PINCTRL_ALT2_3_RES_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO91 / (THR15/VIN15/TD1P) */
	[GPIO91__THR15_VIN15_TD1P] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT2_1_VIN15_SL, NPCM_PINCTRL_ALT2_3_RES_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO92 / (THR14/VIN14/TD0P) */
	[GPIO92__THR14_VIN14_TD0P] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT2_0_VIN14_SL, NPCM_PINCTRL_ALT2_3_RES_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO93 / (THR1/VIN1/TD3P) / DSADC_CLK */
	[GPIO93__THR1_VIN1_TD3P__DSADC_CLK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT1_1_VIN1_SL, NPCM_PINCTRL_ALT2_3_RES_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO94 / (VIN2/THR2/TD4P) */
	[GPIO94__VIN2_THR2_TD4P] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT1_2_VIN2_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIO95 / ATX5VSB / VIN3 */
	[GPIO95__ATX5VSB__VIN3] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT1_4_ATX5VVSB_SL, NPCM_PINCTRL_ALT1_3_VIN3_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO96 / I3C6_SCL / SCL6A */
	[GPIO96__I3C6_SCL__SCL6A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT7_3_GP96_SL, NPCM_PINCTRL_ALT7_2_I3C6_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0x8, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIO97 / PECI / I3C6_SDA / SDA6A */
	[GPIO97__PECI__I3C6_SDA__SDA6A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT7_4_GP97_SL, NPCM_PINCTRL_ALT5_4_PECI_EN,
				 NPCM_PINCTRL_ALT7_2_I3C6_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0x10, 0x8, 0x4, 0, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/* GPIOA0 / PWM4 / IOX2_LDSH */
	[GPIOA0__PWM4__IOX2_LDSH] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT4_6_PWM4_SL, NPCM_PINCTRL_ALT6A_1_SIOX2_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOA1 / TA4 / IOX2_DOUT */
	[GPIOA1__TA4__IOX2_DOUT] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT3_4_TA4_SL, NPCM_PINCTRL_ALT6A_1_SIOX2_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIOA2 / (SWDIO_2/CR_SOUT1) / SDA3A
	 * See JTAG Hot-Plug HPLUG_CONN[3:0] for SWDIO_2/CR_SOUT1.
	 */
	[GPIOA2__SWDIO_2_CR_SOUT1__SDA3A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTA_1_SMB3A_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOA3 / PWM5 / IOX2_DIN */
	[GPIOA3__PWM5__IOX2_DIN] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT4_7_PWM5_SL, NPCM_PINCTRL_ALT6A_1_SIOX2_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOA4 / TA5 / IOX2_SCLK */
	[GPIOA4__TA5__IOX2_SCLK] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT3_5_TA5_SL, NPCM_PINCTRL_ALT6A_1_SIOX2_SL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0x8, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* GPIOA5 / PWM6 */
	[GPIOA5__PWM6] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT5_0_PWM6_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIOA6 / TA6 / USB20
	 * GPIOA6 / TA6 should be disabled if USB2.0_CLK is used.
	 */
	[GPIOA6__TA6__USB20] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALT3_6_TA6_SL, NPCM_PINCTRL_ALT2E_4_USBDPHY_EN,
				 NPCM_PINCTRL_ALT2E_6_USBDPHY_CLKSEL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0x10, 0xC, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/*
	 * GPIOA7 / (SWCLK_2/CR_SIN1) / SCL3A
	 * See JTAG Hot-Plug HPLUG_CONN[3:0] for SWCLK_2/CR_SIN1.
	 */
	[GPIOA7__SWCLK_2_CR_SIN1__SCL3A] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_ALTA_1_SMB3A_SL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(0, 0, 0x10, NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL)),
	/* Reserved: GPIOE7, GPIO group_e only has 7 GPIOs */
	[RES_GPIOE7] = NPCM_PINCTRL_GROUP_RDATA(
		NPCM_PINCTRL_REG(NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL, NPCM_PINCTRL_REG_NULL,
				 NPCM_PINCTRL_REG_NULL),
		NPCM_PINCTRL_ALT(NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL,
				 NPCM_PINCTRL_CFG_NULL, NPCM_PINCTRL_CFG_NULL)),
};

/* Driver config */
struct npcm_pinctrl_config {
	/* Device base address used for pinctrl driver */
	uintptr_t base_scfg;
	uintptr_t base_glue;
};

static const struct npcm_pinctrl_config npcm_pinctrl_cfg = {
	.base_scfg = DT_INST_REG_ADDR_BY_NAME(0, scfg),
	.base_glue = DT_INST_REG_ADDR_BY_NAME(0, glue),
};

/* SCFG multi-registers */
#define NPCM_SCFG_OFFSET(n)     (((n) >> NPCM_PINCTRL_SHIFT) & NPCM_PINCTRL_MASK)
#define NPCM_SCFG(base, n)      (*(volatile uint8_t *)(base + NPCM_SCFG_OFFSET(n)))
#define NPCM_SCFG_BIT_OFFSET(n) ((n) & NPCM_PINCTRL_BIT_MASK)

static void npcm_periph_pinmux_configure(const struct npcm_periph_pinmux *alt)
{
	const uintptr_t scfg_base = npcm_pinctrl_cfg.base_scfg;
	uint8_t cfg_value;
	uint16_t reg_value;
	uint32_t bit_mask;
	int i;

	/* Check index is exist */
	if ((alt->id >= ARRAY_SIZE(npcm_pinctrl_table)) ||
	    (alt->alt_group >= NPCM_PINCTRL_CFG_SIZE)) {
		return;
	}

	/* Check for empty config */
	cfg_value = npcm_pinctrl_table[alt->id].cfg[alt->alt_group];
	if (cfg_value == NPCM_PINCTRL_CFG_NULL) {
		return;
	}

	/* Set bit value in cfg */
	for (i = 0; i < NPCM_PINCTRL_REG_SIZE; i++) {
		reg_value = npcm_pinctrl_table[alt->id].reg[i];
		if (reg_value == NPCM_PINCTRL_REG_NULL) {
			continue;
		}

		bit_mask = BIT(NPCM_SCFG_BIT_OFFSET(reg_value));
		if (cfg_value & BIT(i)) {
			NPCM_SCFG(scfg_base, reg_value) |= bit_mask;
		} else {
			NPCM_SCFG(scfg_base, reg_value) &= ~bit_mask;
		}
	}
}

static void npcm_periph_pupd_configure(const struct npcm_periph_pupd *pupd,
				       enum npcm_io_bias_type type)
{
	const uintptr_t scfg_base = npcm_pinctrl_cfg.base_scfg;
	uint8_t pupd_mask = BIT(NPCM_SCFG_BIT_OFFSET(pupd->id));

	if (type == NPCM_BIAS_TYPE_NONE) {
		NPCM_SCFG(scfg_base, pupd->id) &= ~pupd_mask;
	} else {
		NPCM_SCFG(scfg_base, pupd->id) |= pupd_mask;
	}
}

static void npcm_device_control_configure(const pinctrl_soc_pin_t *pin)
{
	const uintptr_t scfg_base = npcm_pinctrl_cfg.base_scfg;
	const struct npcm_dev_ctl *ctrl = (const struct npcm_dev_ctl *)&pin->cfg.dev_ctl;
	uint8_t devctl_mask = BIT(NPCM_SCFG_BIT_OFFSET(ctrl->id));

	if (ctrl->is_set == 0) {
		NPCM_SCFG(scfg_base, ctrl->id) &= ~devctl_mask;
	} else {
		NPCM_SCFG(scfg_base, ctrl->id) |= devctl_mask;
	}
}

/* Pinctrl API implementation */
int pinctrl_configure_pins(const pinctrl_soc_pin_t *pins, uint8_t pin_cnt, uintptr_t reg)
{
	ARG_UNUSED(reg);
	uint8_t i;

	/* Configure all peripheral devices' properties here. */
	for (i = 0; i < pin_cnt; i++) {
		switch (pins[i].flags.type) {
		case NPCM_PINCTRL_TYPE_PERIPH_PINMUX:
			/* Configure peripheral device's pinmux functionality */
			npcm_periph_pinmux_configure(&pins[i].cfg.pinmux);
			break;

		case NPCM_PINCTRL_TYPE_PERIPH_PUPD:
			/* Configure peripheral device's internal PU/PD */
			npcm_periph_pupd_configure(&pins[i].cfg.pupd, pins[i].flags.io_bias_type);
			break;

		case NPCM_PINCTRL_TYPE_DEVICE_CTRL:
			/* Configure device's io characteristics */
			npcm_device_control_configure(&pins[i]);
			break;

		default:
			return -ENOTSUP;
		}
	}

	return 0;
}

/* Pin-control driver registration */
static int npcm_pinctrl_init(const struct device *dev)
{
	ARG_UNUSED(dev);
	return 0;
}

DEVICE_DT_INST_DEFINE(0, &npcm_pinctrl_init, NULL, NULL, &npcm_pinctrl_cfg, PRE_KERNEL_1,
		      CONFIG_KERNEL_INIT_PRIORITY_DEFAULT, NULL);
